#
# Copyright (c) 2020, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

---
{{- $secretName := (include "fullname" .) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
{{- include "oracle-db-labels" . | indent 2 }}
stringData:
{{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $secretName) | default dict }}
{{- $secretData := (get $secretObj "data") | default dict }}
{{- $pwdSecret := (get $secretData "oracle_pwd") | b64dec | default .Values.oracle_pwd | default (randAlphaNum 10)  }}
  oracle_pwd: {{ $pwdSecret | quote }}
---

