#!/bin/bash
#############################

# Copyright 2025, Oracle Corporation and/or affiliates.  All rights reserved.

# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl

# Author: paramdeep.saini@oracle.com

echo "Creating env variables file /etc/rac_env_vars"
while IFS= read -r -d '' envvar; do
  key=${envvar%%=*}
  value=${envvar#*=}
  printf 'export %s=%q\n' "$key" "$value"
done < /proc/1/environ > /etc/rac_env_vars

echo "Starting Systemd"
exec /lib/systemd/systemd
