#! /bin/bash

echo "Creating env variables file /etc/rac_env_vars"
while IFS= read -r -d '' envvar; do
  key=${envvar%%=*}
  value=${envvar#*=}
  printf 'export %s=%q\n' "$key" "$value"
done < /proc/1/environ > /etc/rac_env_vars

echo "Starting Systemd"
exec /lib/systemd/systemd
