#!/bin/sh
# Copyright (c) 2014-2018 Oracle and/or its affiliates. All rights reserved.
#
#
#Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#
# This script will be in PATH and it will skip module scanning by default, making WLST calls much faster
# If you know what you are doing, call actual wlst.sh
#
wlst.sh -skipWLSModuleScanning $@
