---
version: "3"
services:
  racnoded2:
    container_name: ${RACNODE2_CONTAINER_NAME}
    hostname: ${RACNODE2_HOST_NAME}
    image: ${RACNODE_IMAGE_NAME}
    restart: always
    dns: ${DNS_PUBLIC_IP}
    dns_search: ${DNS_DOMAIN}
    volumes:
      - /boot:/boot:ro
      - /opt/.secrets:/run/secrets:ro
      - /dev/shm
      - /opt/containers/rac_host_file:/etc/hosts
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - racstorage:/oradata
    tmpfs:
      - /dev/shm:rw,exec,size=4G
      - /run
    privileged: false
    environment:
      DNS_SERVERS: ${DNS_PUBLIC_IP}
      EXISTING_CLS_NODES: ${INSTALL_NODE} 
      NODE_VIP: ${RACNODE2_NODE_VIP}
      VIP_HOSTNAME: ${RACNODE2_VIP_HOSTNAME}
      PRIV_IP: ${RACNODE2_PRIV_IP}
      PRIV_HOSTNAME: ${RACNODE2_PRIV_HOSTNAME}
      OP_TYPE: ADDNODE
      PUBLIC_IP: ${RACNODE2_PUBLIC_IP}
      PUBLIC_HOSTNAME: ${RACNODE2_PUBLIC_HOSTNAME}
      SCAN_NAME: ${SCAN_NAME}
      DOMAIN: ${DNS_DOMAIN}
      ASM_DEVICE_LIST: ${ASM_DEVICE_LIST}
      ASM_DISCOVERY_DIR: ${ASM_DISCOVERY_DIR}
      ORACLE_SID: ${ORACLE_DBNAME}
      COMMON_OS_PWD_FILE: ${COMMON_OS_PWD_FILE}
      PWD_KEY: ${PWD_KEY}
      RESET_FAILED_SYSTEMD: "true"
    ulimits:
      rtprio: 99
    cap_add:
      - SYS_RESOURCE
      - NET_ADMIN
      - SYS_NICE
    cpu_rt_runtime: 95000
    networks:
      - rac_pub1_nw
      - rac_priv1_nw
    healthcheck:
      test: ["CMD-SHELL", "su - grid -c 'srvctl status database -d ORCLCDB'| grep -q 'is running on node'"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
networks:
  rac_pub1_nw:
    name: ${PUBLIC_NETWORK_NAME}
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "${PUBLIC_NETWORK_SUBNET}"
  rac_priv1_nw:
    name: ${PRIVATE_NETWORK_NAME}
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "${PRIVATE_NETWORK_SUBNET}"
volumes:
  racstorage:
    external: true