---
version: "3"
networks:
  rac_pub1_nw:
    name: ${PUBLIC_NETWORK_NAME}
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "${PUBLIC_NETWORK_SUBNET}"
  rac_priv1_nw:
    name: ${PRIVATE1_NETWORK_NAME}
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "${PRIVATE1_NETWORK_SUBNET}"
  rac_priv2_nw:
    name: ${PRIVATE2_NETWORK_NAME}
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "${PRIVATE2_NETWORK_SUBNET}"
secrets:
  pwdsecret:
    file: ${PWD_SECRET_FILE}
  keysecret:
    file: ${KEY_SECRET_FILE}
services:
  rac-dnsserver:
    container_name: ${DNS_CONTAINER_NAME}
    hostname: ${DNS_HOST_NAME}
    image: ${DNS_IMAGE_NAME}
    dns_search: ${DNS_DOMAIN}
    environment:
      SETUP_DNS_CONFIG_FILES: "setup_true"
      DOMAIN_NAME: ${DNS_DOMAIN}
      RAC_NODE_NAME_PREFIXD: ${RAC_NODE_NAME_PREFIXD}
      RAC_NODE_NAME_PREFIXP: ${RAC_NODE_NAME_PREFIXP}
      WEBMIN_ENABLED: false
      SETUP_DNS_CONFIG_FILES: "setup_true"
    cap_add:
      - AUDIT_WRITE
    healthcheck:
      test: ["CMD-SHELL", "if [ `cat /tmp/orod.log | grep -c 'DNS Server IS READY TO USE'` -ge 1 ]; then exit 0; else exit 1; fi"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
    privileged: false
    networks:
      - rac_pub1_nw
      - rac_priv1_nw
      - rac_priv2_nw
  racnodep1:
    container_name: ${RACNODE1_CONTAINER_NAME}
    hostname: ${RACNODE1_HOST_NAME}
    image: ${RAC_IMAGE_NAME}
    restart: always
    dns: ${DNS_PUBLIC_IP}
    dns_search: ${DNS_DOMAIN}
    shm_size: 4G
    secrets:
      - pwdsecret
      - keysecret
    volumes:
      - ${GRID_RESPONSE_FILE}:/tmp/grid_21c.rsp
    environment:
      DNS_SERVERS: ${DNS_PUBLIC_IP}
      PRIVATE_IP1_LIST: ${RACNODE1_PRIVATE_IP1_LIST}
      PRIVATE_IP2_LIST: ${RACNODE1_PRIVATE_IP2_LIST}
      DEFAULT_GATEWAY: ${DEFAULT_GATEWAY}
      OP_TYPE: setuprac
      INSTALL_NODE: ${INSTALL_NODE}
      CRS_NODES: ${CRS_NODES}
      SCAN_NAME: ${SCAN_NAME}
      CRS_ASM_DEVICE_LIST: ${CRS_ASM_DEVICE_LIST}
      CRS_ASM_DISCOVERY_DIR: ${CRS_ASM_DISCOVERY_DIR}
      INIT_SGA_SIZE: 3G
      INIT_PGA_SIZE: 2G
      DB_PWD_FILE: pwdsecret
      PWD_KEY: keysecret
      GRID_RESPONSE_FILE: /tmp/grid_21c.rsp
      CMAN_HOST: ${CMAN_HOST_NAME}
      CMAN_PORT: 1521
    sysctls:
        - kernel.shmall=2097152
        - kernel.shmmax=8589934592
        - kernel.shmmni=4096
        - 'kernel.sem=250 32000 100 128'
        - 'net.ipv4.conf.eth1.rp_filter=2'
        - 'net.ipv4.conf.eth2.rp_filter=2'
    ulimits:
      rtprio: 99
    cap_add:
      - SYS_RESOURCE
      - NET_ADMIN
      - SYS_NICE
      - AUDIT_WRITE
      - AUDIT_CONTROL
    devices:
      - "${ASM_DISK1}:${ASM_DEVICE1}"
      - "${ASM_DISK2}:${ASM_DEVICE2}"
    networks:
      - rac_pub1_nw
      - rac_priv1_nw
      - rac_priv2_nw
    healthcheck:
      test: ["CMD-SHELL", "if [ `cat /tmp/orod/oracle_rac_setup.log | grep -c 'ORACLE RAC DATABASE IS READY TO USE'` -ge 1 ]; then exit 0; else exit 1; fi"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
  racnodep2:
    container_name: ${RACNODE2_CONTAINER_NAME}
    hostname: ${RACNODE2_HOST_NAME}
    image: ${RAC_IMAGE_NAME}
    restart: always
    dns: ${DNS_PUBLIC_IP}
    dns_search: ${DNS_DOMAIN}
    shm_size: 4G
    secrets:
      - pwdsecret
      - keysecret
    volumes:
      - ${GRID_RESPONSE_FILE}:/tmp/grid_21c.rsp
    environment:
      DNS_SERVERS: ${DNS_PUBLIC_IP}
      PRIVATE_IP1_LIST: ${RACNODE2_PRIVATE_IP1_LIST}
      PRIVATE_IP2_LIST: ${RACNODE2_PRIVATE_IP2_LIST}
      DEFAULT_GATEWAY: ${DEFAULT_GATEWAY}
      INSTALL_NODE: ${INSTALL_NODE}
      CRS_NODES: ${CRS_NODES}
      SCAN_NAME: ${SCAN_NAME}
      CRS_ASM_DEVICE_LIST: ${CRS_ASM_DEVICE_LIST}
      CRS_ASM_DISCOVERY_DIR: ${CRS_ASM_DISCOVERY_DIR}
      INIT_SGA_SIZE: 3G
      INIT_PGA_SIZE: 2G
      DB_PWD_FILE: pwdsecret
      PWD_KEY: keysecret
      GRID_RESPONSE_FILE: /tmp/grid_21c.rsp
      CMAN_HOST: ${CMAN_HOST_NAME}
      CMAN_PORT: 1521
    sysctls:
        - kernel.shmall=2097152
        - kernel.shmmax=8589934592
        - kernel.shmmni=4096
        - 'kernel.sem=250 32000 100 128'
        - 'net.ipv4.conf.eth1.rp_filter=2'
        - 'net.ipv4.conf.eth2.rp_filter=2'
    ulimits:
      rtprio: 99
    cap_add:
      - SYS_RESOURCE
      - NET_ADMIN
      - SYS_NICE
      - AUDIT_WRITE
      - AUDIT_CONTROL
    devices:
      - "${ASM_DISK1}:${ASM_DEVICE1}"
      - "${ASM_DISK2}:${ASM_DEVICE2}"
    networks:
      - rac_pub1_nw
      - rac_priv1_nw
      - rac_priv2_nw
  racnodepc1-cman:
    container_name: ${CMAN_CONTAINER_NAME}
    hostname: ${CMAN_HOST_NAME}
    image: ${CMAN_IMAGE_NAME}
    dns_search: ${DNS_DOMAIN}
    dns: ${DNS_PUBLIC_IP}
    environment:
      DOMAIN_NAME: ${DNS_DOMAIN}
      PUBLIC_IP: ${CMAN_PUBLIC_IP}
      PUBLIC_HOSTNAME: ${CMAN_PUBLIC_HOSTNAME}
      DB_HOSTDETAILS: ${DB_HOSTDETAILS}
    privileged: false
    ports:
      - 1521:1521
    networks:
      rac_pub1_nw:
        ipv4_address: ${CMAN_PUBLIC_IP}
    cap_add:
      - AUDIT_WRITE
    healthcheck:
      test: ["CMD-SHELL", "if [ `cat /tmp/orod.log | grep -c 'CONNECTION MANAGER IS READY TO USE'` -ge 1 ]; then exit 0; else exit 1; fi"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}