# LICENSE UPL 1.0
#
# Copyright (c) 2018,2022 Oracle and/or its affiliates.
#
# ORACLE CONTAINERFILES PROJECT
# --------------------------
# This is the Containerfile for Oracle Database 23c Release 3 Oracle Connection Manager
#
# HOW TO BUILD THIS IMAGE
# -----------------------
# Run:
#      $ docker build -t oracle/cman:23c .

ARG BASE_OL_IMAGE=oraclelinux:8

# Pull base image
# ---------------
FROM $BASE_OL_IMAGE AS base

# Labels
# ------
LABEL "provider"="Oracle"                                               \
      "volume.setup.location1"="/opt/scripts"              \
      "volume.startup.location1"="/opt/scripts/startup"

# Argument to control removal of components not needed after db software installation
ARG SLIMMING=false
ARG INSTALL_FILE_1="LINUX.X64_233000_client.zip"
ARG USER="root"
ARG WORKDIR="/root"

ENV INSTALL_DIR=/opt/scripts \
    WORKDIR=$WORKDIR \
    DB_BASE=/u01/app/oracle \
    DB_USER=oracle \
    CHECK_SPACE_FILE="checkSpace.sh" \
    CMANORA="cman.ora" \
    FUNCTIONS="functions.sh" \
    INVENTORY=/u01/app/oraInventory \
    DB_HOME=/u01/app/oracle/product/23c/client_1 \
    JAVA_HOME=/u01/app/oracle/product/23c/client_1/jdk \
    LD_LIBRARY_PATH=/u01/app/oracle/product/23c/client_1/lib \
    SQLPATH=/u01/app/oracle/product/23c/client_1/lib \
    INSTALL_SCRIPTS=/opt/scripts/install \
    INSTALL_FILE_1=$INSTALL_FILE_1 \
    CONFIG_CMAN_FILE="configCMAN.sh" \
    RUN_FILE="runOracle.sh" \
    DB_SETUP_FILE="setupDB.sh" \
    INSTALL_DB_BINARIES_FILE="installDBBinaries.sh" \
    SETUP_LINUX_FILE="setupLinuxEnv.sh" \
    container="true"

#####

ENV  INSTALL_SCRIPTS=$INSTALL_DIR/install \
     PATH=/bin:/usr/bin:/sbin:/usr/sbin:$PATH \
     SCRIPT_DIR=$INSTALL_DIR/startup \
     INSTALL_SCRIPTS=$INSTALL_DIR/install \
     DB_PATH=$DB_HOME/bin:$DB_HOME/OPatch/:/usr/sbin:$PATH \
     DB_LD_LIBRARY_PATH=$DB_HOME/lib:/usr/lib:/lib

######

COPY $RUN_FILE $CMANORA $CONFIG_CMAN_FILE $FUNCTIONS $INSTALL_DIR/startup/

RUN dnf  -y install oracle-database-preinstall-21c net-tools which zip unzip tar openssh-server vim-minimal which vim-minimal passwd sudo hostname  && \
    dnf clean all  && \
    mkdir -p "$DB_BASE" && \
    mkdir -p "$DB_HOME" && \
    mkdir -p $INVENTORY  && \
    chown -R "${DB_USER}":oinstall "$DB_BASE" && \
    chown -R "${DB_USER}":oinstall "$DB_HOME" && \
    chown -R "${DB_USER}":oinstall "$INVENTORY" && \
    chmod 755 $INSTALL_DIR/startup/*.sh && \
    mkdir -p $INSTALL_DIR/install && \
    chmod 755 $INSTALL_DIR/install && \
    chown -R "${DB_USER}":oinstall $INSTALL_DIR/install && \
    chmod 666 /etc/sudoers  && \
    echo "oracle       ALL=(ALL)       NOPASSWD: ALL" >> /etc/sudoers && \
    chmod 440 /etc/sudoers && \
    chmod 4711 /usr/bin/ping && \
    sync

#############################################
# -------------------------------------------
# Start new stage for installing the  client and swingbench
# -------------------------------------------
#############################################

from base AS builder

USER oracle

COPY $INSTALL_FILE_1 $SETUP_LINUX_FILE $CHECK_SPACE_FILE $INSTALL_DB_BINARIES_FILE $INSTALL_DIR/install/

WORKDIR /u01/app/
RUN  unzip -q $INSTALL_SCRIPTS/$INSTALL_FILE_1 -d $DB_HOME && \
     $DB_HOME/runInstaller -ignorePrereq -waitforcompletion  -silent \
     UNIX_GROUP_NAME="oinstall" \
     INVENTORY_LOCATION=$INVENTORY \
     ORACLE_HOME=$DB_HOME \
     ORACLE_BASE=$DB_BASE \
     oracle.install.client.installType=Custom \
     oracle.install.client.customComponents="oracle.sqlplus:23.0.0.0.0,oracle.network.client:23.0.0.0.0,oracle.network.cman:23.0.0.0.0,oracle.network.listener:23.0.0.0.0" || \
     sync

#############################################
# -------------------------------------------
# Start new layer for client
# -------------------------------------------
#############################################

FROM base

COPY  --from=builder /u01 /u01

RUN  sh /u01/app/oraInventory/orainstRoot.sh && \
     sed -e '/hard *memlock/s/^/#/g' -i /etc/security/limits.d/oracle-database-preinstall-21c.conf && \
     sed -e '/ *nofile /s/^/#/g' -i /etc/security/limits.d/oracle-database-preinstall-21c.conf && \
     sync && \
     echo "export ORACLE_HOME=$DB_HOME" >> /home/oracle/.bashrc && \
     echo "export JAVA_HOME=$JAVA_HOME" >> /home/oracle/.bashrc && \
     echo "export PATH=$DB_HOME/bin:$JAVA_HOME/bin:$PATH" >> /home/oracle/.bashrc && \
     sync

USER oracle
EXPOSE 1521 5500
VOLUME ["/common_scripts"]
WORKDIR /home/oracle

# Define default command to start Oracle Grid and RAC Database setup.

CMD exec $SCRIPT_DIR/$RUN_FILE
