# LICENSE UPL 1.0
#
# Copyright (c) 1982-2019 Oracle and/or its affiliates. All rights reserved.
#
# ORACLE DOCKERFILES PROJECT
# --------------------------
# This is the Dockerfile for a patched Oracle Database 21c Release 3
# 
# REQUIREMETNS FOR THIS IMAGE
# ----------------------------------
# The oracle/rac-database:21.3.0 image has to exist
#
# HOW TO BUILD THIS IMAGE
# -----------------------
# Put the downloaded patch(es) into the sub folders patch/0NN
# Run: 
#      $ docker build -f Dockerfile -t oracle/rac-database:21.3.0-<patch level> . 
#
ARG BASE_RAC_IMAGE=localhost/oracle/database-rac:19.3.0
ARG RAC_SLIM_IMAGE=localhost/oracle/database-rac:19.3.0-slim

# Pull base image
# ---------------
# hadolint ignore=DL3006
FROM $BASE_RAC_IMAGE as builder

# Argument to control removal of components not needed after db software installation
ARG SLIMMING=false
ARG PATCH_DIR="patches"
ARG DB_EDITION="EE"
ARG USER="root"
ARG WORKDIR="/rac-work-dir"

# Environment variables required for this build (do NOT change)
# -------------------------------------------------------------
# hadolint ignore=DL3002
USER root 

ENV PATCH_DIR=$PATCH_DIR \
    GRID_PATCH_FILE="applyGridPatches.sh" \
    DB_PATCH_FILE="applyDBPatches.sh" \
    FIXUP_PREQ_FILE="fixupPreq.sh" \
    DB_USER="oracle" \
    USER=$USER \
    WORKDIR=$WORKDIR \
    GRID_USER="grid"  

# Use second ENV so that variable get substituted
ENV PATCH_INSTALL_DIR=/tmp/patches

# Copy binaries
# -------------
COPY $PATCH_DIR $PATCH_INSTALL_DIR/

# Install patches
RUN chown -R grid:oinstall $PATCH_INSTALL_DIR/*.sh && \
    chmod ug+x $PATCH_INSTALL_DIR/*.sh && \
    chmod ug+rwx $PATCH_INSTALL_DIR && \
    chown -R grid:oinstall $PATCH_INSTALL_DIR && \
    sed -e '/hard *memlock/s/^/#/g' -i /etc/security/limits.conf  && \
    sed -e '/ *nofile /s/^/#/g' -i /etc/security/limits.conf  && \
    sync && \
    su grid -c "$PATCH_INSTALL_DIR/$GRID_PATCH_FILE $PATCH_INSTALL_DIR" && \
    chown -R oracle:oinstall $PATCH_INSTALL_DIR

USER oracle

RUN $PATCH_INSTALL_DIR/$DB_PATCH_FILE $PATCH_INSTALL_DIR
# hadolint ignore=DL3002
USER root

RUN $PATCH_INSTALL_DIR/$FIXUP_PREQ_FILE  && \
    rm -rf /etc/oracle && \
    rm -rf $PATCH_INSTALL_DIR

#####################
# hadolint ignore=DL3006
FROM $RAC_SLIM_IMAGE AS final

# Define build-time arguments
ARG GRID_HOME
ARG DB_HOME

#Set environment variables using build arguments
ENV GRID_BASE=/u01/app/grid \
    GRID_HOME=$GRID_HOME \
    DB_BASE=/u01/app/oracle \
    DB_HOME=$DB_HOME \
    INSTALL_SCRIPTS=/opt/scripts/install \
    SCRIPT_DIR=/opt/scripts/startup \
    RAC_SCRIPTS_DIR="scripts"

ENV GRID_PATH=$GRID_HOME/bin:$GRID_HOME/OPatch/:$GRID_HOME/perl/bin:/usr/sbin:/bin:/sbin \
    DB_PATH=$DB_HOME/bin:$DB_HOME/OPatch/:$DB_HOME/perl/bin:/usr/sbin:/bin:/sbin \
    GRID_LD_LIBRARY_PATH=$GRID_HOME/lib:/usr/lib:/lib \
    DB_LD_LIBRARY_PATH=$DB_HOME/lib:/usr/lib:/lib

# Run some basic command to verify the environment variables (optional)
RUN echo "GRID_BASE=$GRID_BASE" && \
    echo "GRID_HOME=$GRID_HOME" && \
    echo "DB_BASE=$DB_BASE" && \
    echo "DB_HOME=$DB_HOME"

RUN if [ -d "/u01" ]; then \
  rm -rf /u01 && \
  :; \
fi

COPY --from=builder /u01 /u01

USER ${USER}
VOLUME ["/common_scripts"]
WORKDIR $WORKDIR

HEALTHCHECK --interval=2m --start-period=30m \
   CMD "$SCRIPT_DIR/scripts/main.py --checkracinst=true" >/dev/null || exit 1
#Fix SID detection
# hadolint ignore=SC2086
RUN $INVENTORY/orainstRoot.sh && \
    $GRID_HOME/root.sh && \
    $DB_HOME/root.sh
# Define default command to start Oracle Grid and RAC Database setup.
# hadolint ignore=DL3025
ENTRYPOINT /usr/bin/$INITSH