------------------------------------------------------------------------
-- DISCLAIMER:
--    This script is provided for educational purposes only. It is NOT
--    supported by Oracle World Wide Technical Support.
--    The script has been tested and appears to work as intended.
--    You should always run new scripts on a test instance initially.
--
------------------------------------------------------------------------
-- Auction Application Database
-- Create as orcl or orcl2 (for backup database)
-- User name: oracle
-- Password: Welcome1
--

-- Drop existing tables and Constraints
--

DROP TABLE Bid;
DROP TABLE Auction;
DROP TABLE Image;

-- Image holds one or more photos for an item
-- Note that ImageID is always autogenerated

CREATE TABLE Image (
    ImageID INTEGER primary key,
    Content BLOB NOT NULL,
    ContentType VARCHAR(50) NOT NULL
);

-- Auction is the time-based sale of an item
-- Status: 1 = Active, 2 = Completed, 3 = Cancelled
-- FK: SellerID, ItemID

CREATE TABLE Auction (
    AuctionID INTEGER primary key,
    ImageID INTEGER NOT NULL,
    Title VARCHAR(60),
    Description VARCHAR(1000),
    Seller VARCHAR(20) NOT NULL,
    HighestBidder VARCHAR(20) NOT NULL,
    CurrPrice REAL NOT NULL,
    BidIncrement REAL NOT NULL,
    Status VARCHAR(15) NOT NULL,
    ItemCondition VARCHAR(15) NOT NULL,
    Version INTEGER NOT NULL
);

CREATE TABLE Bid (
    BidID INTEGER primary key,
    Bidder VARCHAR(40) NOT NULL,
    AuctionID INTEGER NOT NULL,
    Amount REAL NOT NULL,
    BidTime TIMESTAMP NOT NULL
);

create sequence imageid_sequence start with 1;
create sequence auctionid_sequence start with 1;
create sequence bidid_sequence start with 1;
create sequence SEQ_GEN_IDENTITY start with 500;
quit;

