#!/bin/bash
# Copyright (c) 2014-2024 , Oracle and/or its affiliates
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/

echo "Creating env variables file /etc/storage_env_vars"
/bin/bash -c "cat /proc/1/environ | tr '\0' '\n' > /etc/storage_env_vars"
/bin/bash -c "sed -i -e 's/^/export /' /etc/storage_env_vars"

echo "Starting Systemd"
exec /lib/systemd/systemd
