FROM oraclelinux:8 as base

ENV ORACLE_BASE=/opt/oracle \
    ORACLE_HOME=/opt/oracle/product/26ai/dbhomeFree \
    ORACLE_SID=FREE \
    START_FILE="oracle-free-26ai" \
    RUN_FILE="runOracle_lite.sh" \
    PWD_FILE="setPassword.sh" \
    USER_SCRIPTS_FILE="runUserScripts.sh" \
    CHECK_SPACE_FILE="checkSpace.sh" \
    CHECK_DB_FILE="checkDBStatus.sh" \
    SETUP_LINUX_FILE="setupLinuxEnv.sh" \
    DECRYPT_PWD_FILE="decryptPassword.sh" \
    TRIM_FILE="trimOS.sh" \
    TRIM_DATA_FILE="os_trim.dat" \
    SCRIPT_BASE_DIR="/opt/oracle/scripts/base" \
    INSTALL_DIR="$HOME/install"

USER root
# Use second ENV so that variable get substituted
ENV PATH=$ORACLE_HOME/bin:$PATH

# Copy binaries
# -------------
COPY $CHECK_SPACE_FILE $SETUP_LINUX_FILE $START_FILE $RUN_FILE $PWD_FILE $CHECK_DB_FILE $USER_SCRIPTS_FILE $DECRYPT_PWD_FILE $INSTALL_DIR/

WORKDIR $INSTALL_DIR

# hadolint ignore=DL3003,DL3033,SC2035
RUN mkdir -p "$ORACLE_BASE" && \
    mkdir -p "${SCRIPT_BASE_DIR}" && \
    mv "$START_FILE" "$RUN_FILE" "$PWD_FILE" "$CHECK_DB_FILE" "$USER_SCRIPTS_FILE" "$DECRYPT_PWD_FILE" "${SCRIPT_BASE_DIR}"/ && \
    chmod ug+x "${SCRIPT_BASE_DIR}"/*.sh && \
        for script in "$PWD_FILE" "$CHECK_DB_FILE" "$USER_SCRIPTS_FILE" "$DECRYPT_PWD_FILE"; do \
      ln -sf "${SCRIPT_BASE_DIR}/$script" "$ORACLE_BASE/$script"; \
    done && \
    chmod ug+x *.sh && \
    sync && \
    ./"$CHECK_SPACE_FILE" && \
    ./"$SETUP_LINUX_FILE" && \
    chown -R oracle:oinstall "$ORACLE_BASE" /home/oracle && \
    sed -i -r 's/(^session\s+include\s+system-auth)/# \1/' /etc/pam.d/su && \
    rm -rf "$INSTALL_DIR"

COPY $TRIM_DATA_FILE $TRIM_FILE /root
ENTRYPOINT /usr/bin/bash $HOME/$TRIM_FILE
