# LICENSE UPL 1.0
#
# Copyright (c) 2022-2026 Oracle and/or its affiliates.
#
# ORACLE DOCKERFILES PROJECT
# --------------------------
# This is the Contatinerfile for Oracle Database 23ai Free Lite
# 
# REQUIRED FILES TO BUILD THIS IMAGE
# ----------------------------------
# None
#
# HOW TO BUILD THIS IMAGE
# -----------------------
# Run: 
#      $ podman build -t oracle/database:23.26.0-free -f Dockerfile.lite .
#
#
# Pull base image
# ---------------
FROM ol-trim:latest as base

# Labels
# ------
LABEL "provider"="Oracle"                                               \
      "maintainer"="Oracle Database Container Team <container-team_ww@oracle.com>" \
      "vendor"="Oracle Corporation"                                     \
      "version"="23.26.0"                                               \
      "release"="Free"                                                  \
      "name"="Oracle AI Database 26ai Free Lite"                             \
      "summary"="Oracle AI Database 26ai Free Lite"                          \
      "description"="Oracle AI Database 26ai Free Lite is a fully functional version of Oracle AI Database 26ai for developers to learn, build, and deploy applications." \
      "issues"="https://github.com/oracle/docker-images/issues"         \
      "volume.data"="/opt/oracle/oradata"                               \
      "volume.startup.location1"="/opt/oracle/scripts/startup"          \
      "volume.startup.location2"="/docker-entrypoint-initdb.d/startup"  \
      "port.listener"="1521"                                            


# Environment variables required for this build (do NOT change)
# -------------------------------------------------------------
ENV ORACLE_BASE=/opt/oracle \
    ORACLE_HOME=/opt/oracle/product/26ai/dbhomeFree \
    ORACLE_SID=FREE \
    INSTALL_BASE_LOC_1="oracle_opt/oh_segregate/base" \
    INSTALL_BASE_LOC_2="oracle_opt/oh_segregate/oracle" \
    INSTALL_ORADATA_LOC_1="oracle_opt/oradata" \
    INSTALL_SYSTEM_LOC_1="oracle_opt" \
    START_FILE="oracle-free-26ai" \
    RUN_FILE="runOracle_lite.sh" \
    PWD_FILE="setPassword.sh" \
    USER_SCRIPTS_FILE="runUserScripts.sh" \
    CHECK_SPACE_FILE="checkSpace.sh" \
    CHECK_DB_FILE="checkDBStatus.sh" \
    SETUP_LINUX_FILE="setupLinuxEnv.sh" \
    DECRYPT_PWD_FILE="decryptPassword.sh" \
    SCRIPT_BASE_DIR="/opt/oracle/scripts/base" \
    INSTALL_DIR="$HOME/install" \
    CHECKPOINT_FILE_EXTN=".created" \
    RUN_AS_ORACLE="true"

# Use second ENV so that variable get substituted
ENV PATH=$ORACLE_HOME/bin:$PATH

#############################################
# -------------------------------------------
# New stage for setting up the oracle home entities
# -------------------------------------------
#############################################

FROM base AS builder

COPY --chown=oracle:oinstall $INSTALL_BASE_LOC_1 $ORACLE_HOME/

RUN chmod ug+x "$ORACLE_HOME"/bin/* &&\
    mkdir "$ORACLE_HOME"/rdbms/log

# ------------------------------------------------------------------------------
# Second stage for setting up the oracle binary
# ------------------------------------------------------------------------------
FROM base AS builder-oracle

COPY --chown=oracle:oinstall $INSTALL_BASE_LOC_2 $ORACLE_HOME/
RUN chmod ug+x "$ORACLE_HOME"/bin/oracle

#############################################
# -------------------------------------------
# Start new layer for database runtime
# -------------------------------------------
#############################################

FROM base

USER oracle

COPY --chown=oracle:oinstall $INSTALL_ORADATA_LOC_1 /opt/oracle/tmp_oradata

COPY --chown=oracle:oinstall --from=builder $ORACLE_HOME $ORACLE_HOME
COPY --chown=oracle:oinstall --from=builder-oracle $ORACLE_HOME $ORACLE_HOME

COPY --chown=oracle:oinstall $INSTALL_SYSTEM_LOC_1/oratab /etc/oratab
COPY --chown=root:root $INSTALL_SYSTEM_LOC_1/LICENSE /usr/share/doc/oracle-free-26ai/LICENSE

USER oracle
WORKDIR /home/oracle

# To enforce ORACLE_SID as FREE, adding it to .bashrc with ORACLE_PDB
RUN echo 'export ORACLE_SID=FREE; ORACLE_PDB=${ORACLE_PDB:-FREEPDB1}; \
    export ORACLE_PDB=${ORACLE_PDB^^}' >> /home/oracle/.bashrc && \
    chown oracle.oinstall /home/oracle/.bashrc


HEALTHCHECK --interval=15s --start-period=45s --timeout=30s \
   CMD "${SCRIPT_BASE_DIR}/${CHECK_DB_FILE:-checkDBStatus.sh}" >/dev/null || exit 1

EXPOSE 1521/tcp

CMD [ "/bin/bash", "-c", "${SCRIPT_BASE_DIR}/$RUN_FILE" ]
