#!/bin/sh
#
# This script will be in PATH and it will skip module scanning by default, making WLST calls much faster
# If you know what you are doing, call actual wlst.sh
#
wlst.sh -skipWLSModuleScanning $@
