# LICENSE UPL 1.0
#
# Copyright (c) 2018,2022 Oracle and/or its affiliates.
#
# ORACLE CONTAINERFILES PROJECT
# --------------------------
# This is the Containerfile for Oracle Database 26ai Release 3 Real Application Clusters to build the container image
# 
# REQUIRED FILES TO BUILD THIS IMAGE
# ----------------------------------
# (1) LINUX.X64_260000_db_home.zip
# (2) LINUX.X64_260000_grid_home.zip 
#     Download Oracle Grid 26ai Release 4 Enterprise Edition for Linux x64
#     Download Oracle Database 26ai Release 4  Enterprise Edition for Linux x64
#     from http://www.oracle.com/technetwork/database/enterprise-edition/downloads/index.html
#
# HOW TO BUILD THIS IMAGE
# -----------------------
# Run: 
#      $ podman build -t oracle/database:26.0.0-rac . 
#
ARG SLIMMING=false
ARG BASE_OL_IMAGE=oraclelinux:9
# Pull base image
# ---------------
FROM $BASE_OL_IMAGE AS base
ARG SLIMMING=false
ARG VERSION
# Labels
# ------
LABEL "provider"="Oracle"                                               \
      "issues"="https://github.com/oracle/docker-images/issues"         \
      "volume.setup.location1"="/opt/scripts"              \
      "volume.startup.location1"="/opt/scripts/startup"          \
      "port.listener"="1521"                                            \
      "port.oemexpress"="5500"

# Argument to control removal of components not needed after db software installation
ARG INSTALL_FILE_1="LINUX.X64_260000_grid_home.zip"
ARG INSTALL_FILE_2="LINUX.X64_260000_db_home.zip"
ARG DB_EDITION="EE"
ARG USER="root"
ARG WORKDIR="/raconcontainers"

# Environment variables required for this build (do NOT change)
# -------------------------------------------------------------
# Linux Env Variable
# hadolint ignore=DL3044
ENV SETUP_LINUX_FILE="setupLinuxEnv.sh" \
    INSTALL_DIR=/opt/scripts \
# Grid Env variables
    GRID_SETUP_FILE="setupGrid.sh" \
    INITSH="initsh" \
    WORKDIR=$WORKDIR \
    GRID_SAMPLE_RESPONSE_FILE="grid_26ai.rsp" \
    DBCA_SAMPLE_RESPONSE_FILE="dbca_26ai.rsp" \
    FIXUP_PREQ_FILE="fixupPreq.sh" \
    INSTALL_GRID_BINARIES_FILE="installGridBinaries.sh" \
    INSTALL_GRID_PATCH="applyGridPatch.sh" \
    INVENTORY=/u01/app/oraInventory \
    INSTALL_FILE_1=$INSTALL_FILE_1 \
    INSTALL_FILE_2=$INSTALL_FILE_2 \
    DB_EDITION=$DB_EDITION \
    GRID_USER_HOME="/home/grid" \
    SETUPGRIDENV="setupGridEnv.sh" \
    RESET_OS_PASSWORD="resetOSPassword.sh" \
# RAC DB Env Variables
    DB_SETUP_FILE="setupDB.sh" \
    RUN_FILE="runOracle.sh" \
    ENABLE_RAC_FILE="enableRAC.sh" \
    INSTALL_DB_BINARIES_FILE="installDBBinaries.sh" \
    GRID_HOME_CLEANUP="GridHomeCleanup.sh" \
    ORACLE_HOME_CLEANUP="OracleHomeCleanup.sh" \
    ORAASMCA="oraasmca.py" \
    CMDEXEC="cmdExec" \
    SETUPSSH="setupSSH.expect" \
    ORAMACHINE="oramachine.py" \
    ORALOGGER="oralogger.py" \
    ORAFACTORY="orafactory.py" \
    ORACVU="oracvu.py" \
    ORAGIADD="oragiadd.py" \
    ORARACDEL="oraracdel.py" \
    ORARACSTDBY="oraracstdby.py" \
    ORAENV="oraenv.py" \
    ORARACPROV="oraracprov.py" \
    MAINPY="main.py" \
    ORAMISCOPS="oramiscops.py" \
    ORAGIPROV="oragiprov.py" \
    ORARACADD="oraracadd.py" \
    ORACOMMON="oracommon.py" \
    ORASSHSETUP="orasshsetup.py" \
    ORASETUPENV="orasetupenv.py" \
    DB_USER="oracle" \
    GRID_USER="grid" \
    SLIMMING=$SLIMMING \
    COMMON_SCRIPTS="/common_scripts" \
    CHECK_SPACE_FILE="checkSpace.sh" \
    EXPECT="/usr/bin/expect" \
    RESET_FAILED_UNITS="resetFailedUnits.sh" \
    BIN="/usr/sbin"

#############################################
# -------------------------------------------
# Start new stage for Non-Slim Image 
# -------------------------------------------
#############################################

FROM base AS rac-image-slim-false
ARG SLIMMING
ARG VERSION
# Environment variables required for this build (do NOT change)
# -------------------------------------------------------------
# Linux Env Variable
ENV GRID_BASE=/u01/app/grid \
    GRID_HOME=/u01/app/26ai/grid \
    DB_BASE=/u01/app/oracle \
    DB_HOME=/u01/app/oracle/product/26ai/dbhome_1
# Use second ENV so that variable get substituted
# hadolint ignore=DL3044
ENV  INSTALL_SCRIPTS=$INSTALL_DIR/install \
     PATH=/bin:/usr/bin:/sbin:/usr/sbin \
     SCRIPT_DIR=$INSTALL_DIR/startup \
     RAC_SCRIPTS_DIR="scripts" \
     GRID_PATH=$GRID_HOME/bin:$GRID_HOME/OPatch/:$GRID_HOME/perl/bin:/usr/sbin:/bin:/sbin  \
     DB_PATH=$DB_HOME/bin:$DB_HOME/OPatch/:$DB_HOME/perl/bin:/usr/sbin:/bin:/sbin \
     GRID_LD_LIBRARY_PATH=$GRID_HOME/lib:/usr/lib:/lib \
     DB_LD_LIBRARY_PATH=$DB_HOME/lib:/usr/lib:/lib

# Copy binaries
# -------------
# COPY Binaries
COPY $VERSION/$SETUP_LINUX_FILE $VERSION/$GRID_SETUP_FILE $VERSION/$DB_SETUP_FILE $VERSION/$CHECK_SPACE_FILE $VERSION/$FIXUP_PREQ_FILE $INSTALL_SCRIPTS/

# Setup Scripts
COPY $VERSION/$RUN_FILE $VERSION/$GRID_SAMPLE_RESPONSE_FILE $VERSION/$DBCA_SAMPLE_RESPONSE_FILE $VERSION/$INITSH $SCRIPT_DIR/

COPY $RAC_SCRIPTS_DIR/$ORAFACTORY $RAC_SCRIPTS_DIR/$MAINPY $RAC_SCRIPTS_DIR/$ORAASMCA  $RAC_SCRIPTS_DIR/$CMDEXEC $RAC_SCRIPTS_DIR/$SETUPSSH $RAC_SCRIPTS_DIR/$ORAMACHINE $RAC_SCRIPTS_DIR/$ORALOGGER $RAC_SCRIPTS_DIR/$ORAFACTORY $RAC_SCRIPTS_DIR/$ORAGIADD  $RAC_SCRIPTS_DIR/$ORARACDEL $RAC_SCRIPTS_DIR/$ORARACSTDBY $RAC_SCRIPTS_DIR/$ORAENV $RAC_SCRIPTS_DIR/$ORARACPROV $RAC_SCRIPTS_DIR/$ORACVU $RAC_SCRIPTS_DIR/$MAINPY $RAC_SCRIPTS_DIR/$ORAMISCOPS $RAC_SCRIPTS_DIR/$ORAGIPROV $RAC_SCRIPTS_DIR/$ORARACADD $RAC_SCRIPTS_DIR/$ORACOMMON $RAC_SCRIPTS_DIR/$ORASSHSETUP $RAC_SCRIPTS_DIR/$ORASETUPENV $VERSION/$RESET_FAILED_UNITS $SCRIPT_DIR/scripts/


RUN chmod 755 $INSTALL_SCRIPTS/*.sh  && \
    sync && \
    $INSTALL_DIR/install/$CHECK_SPACE_FILE && \
    $INSTALL_DIR/install/$SETUP_LINUX_FILE && \
    $INSTALL_DIR/install/$GRID_SETUP_FILE && \
    $INSTALL_DIR/install/$DB_SETUP_FILE && \
    rm -rf $DB_HOME/.patch_storage $DB_HOME/.opatchauto_storage $GRID_HOME/.patch_storage $GRID_HOME/.opatchauto_storage && \
    sync

#############################################
# -------------------------------------------
# Start new stage for slim image
# -------------------------------------------
#############################################
FROM base AS rac-image-slim-true
ARG SLIMMING
ARG VERSION
# Environment variables required for this build (do NOT change)
# -------------------------------------------------------------
# Linux Env Variable
ENV  INSTALL_SCRIPTS=$INSTALL_DIR/install \
     PATH=/bin:/usr/bin:/sbin:/usr/sbin \
     SCRIPT_DIR=$INSTALL_DIR/startup \
     RAC_SCRIPTS_DIR="scripts"

# Copy binaries
# -------------
# COPY Binaries
COPY $VERSION/$SETUP_LINUX_FILE $VERSION/$GRID_SETUP_FILE $VERSION/$DB_SETUP_FILE $VERSION/$CHECK_SPACE_FILE $VERSION/$FIXUP_PREQ_FILE $INSTALL_SCRIPTS/

# Setup Scripts
COPY $VERSION/$RUN_FILE $VERSION/$GRID_SAMPLE_RESPONSE_FILE $VERSION/$DBCA_SAMPLE_RESPONSE_FILE $VERSION/$INITSH $SCRIPT_DIR/

COPY $RAC_SCRIPTS_DIR/$ORAFACTORY $RAC_SCRIPTS_DIR/$MAINPY $RAC_SCRIPTS_DIR/$ORAASMCA  $RAC_SCRIPTS_DIR/$CMDEXEC $RAC_SCRIPTS_DIR/$SETUPSSH $RAC_SCRIPTS_DIR/$ORAMACHINE $RAC_SCRIPTS_DIR/$ORALOGGER $RAC_SCRIPTS_DIR/$ORAFACTORY $RAC_SCRIPTS_DIR/$ORAGIADD  $RAC_SCRIPTS_DIR/$ORARACDEL $RAC_SCRIPTS_DIR/$ORARACSTDBY $RAC_SCRIPTS_DIR/$ORAENV $RAC_SCRIPTS_DIR/$ORARACPROV $RAC_SCRIPTS_DIR/$ORACVU $RAC_SCRIPTS_DIR/$MAINPY $RAC_SCRIPTS_DIR/$ORAMISCOPS $RAC_SCRIPTS_DIR/$ORAGIPROV $RAC_SCRIPTS_DIR/$ORARACADD $RAC_SCRIPTS_DIR/$ORACOMMON $RAC_SCRIPTS_DIR/$ORASSHSETUP $RAC_SCRIPTS_DIR/$ORASETUPENV $VERSION/$RESET_FAILED_UNITS $SCRIPT_DIR/scripts/

# hadolint ignore=SC2086
RUN chmod 755 $INSTALL_SCRIPTS/*.sh  && \
    sync && \
    $INSTALL_DIR/install/$CHECK_SPACE_FILE && \
    $INSTALL_DIR/install/$SETUP_LINUX_FILE && \
    $INSTALL_DIR/install/$GRID_SETUP_FILE && \
    $INSTALL_DIR/install/$DB_SETUP_FILE && \
    rm -rf $DB_HOME/.patch_storage $DB_HOME/.opatchauto_storage $GRID_HOME/.patch_storage $GRID_HOME/.opatchauto_storage && \
    sync


#############################################
# -------------------------------------------
# Start new stage for installing the grid and DB
# -------------------------------------------
#############################################
# hadolint ignore=DL3006
FROM rac-image-slim-${SLIMMING} AS builder
ARG SLIMMING
# hadolint ignore=DL3006
ARG VERSION
COPY $VERSION/$INSTALL_GRID_BINARIES_FILE $VERSION/$DB_SETUP_FILE  $VERSION/$INSTALL_DB_BINARIES_FILE $VERSION/$ENABLE_RAC_FILE $VERSION/$GRID_HOME_CLEANUP $VERSION/$ORACLE_HOME_CLEANUP $VERSION/$INSTALL_FILE_1* $VERSION/$INSTALL_FILE_2*  $INSTALL_SCRIPTS/

RUN chmod 755 $INSTALL_SCRIPTS/*.sh

## Install software if SLIMMING is false
USER ${GRID_USER}
RUN if [ "${SLIMMING}x" != 'truex' ]; then \
      $INSTALL_DIR/install/$INSTALL_GRID_BINARIES_FILE EE $PATCH_NUMBER && \
      $INSTALL_SCRIPTS/$GRID_HOME_CLEANUP && \
      :;\
    fi
USER ${USER}
RUN if [ "${SLIMMING}x" != 'truex' ]; then \
      $INVENTORY/orainstRoot.sh && \
      $GRID_HOME/root.sh && \
      :;\   
    fi
USER ${DB_USER}
RUN if [ "${SLIMMING}x" != 'truex' ]; then \     
      $INSTALL_DIR/install/$INSTALL_DB_BINARIES_FILE EE && \
      $INSTALL_DIR/install/$ENABLE_RAC_FILE && \
      $INSTALL_SCRIPTS/$ORACLE_HOME_CLEANUP && \
      :;\
    fi

USER ${USER}
RUN if [ "${SLIMMING}x" != 'truex' ]; then \
      $INVENTORY/orainstRoot.sh && \
      $DB_HOME/root.sh && \
      :; \
    fi
# hadolint ignore=SC3014
USER ${USER}
RUN if [ "${SLIMMING}x" == 'truex' ]; then \
      mkdir /u01 && \
      :; \
    fi
# hadolint ignore=SC2086
RUN rm -f $INSTALL_DIR/install/* && \
    sync

#############################################
# -------------------------------------------
# Start new layer for grid & database runtime
# -------------------------------------------
#############################################
# hadolint ignore=DL3006
FROM rac-image-slim-${SLIMMING} AS final
ENV GRID_BASE=/u01/app/grid \
    GRID_HOME=/u01/app/26ai/grid \
    DB_BASE=/u01/app/oracle \
    DB_HOME=/u01/app/oracle/product/26ai/dbhome_1
RUN rm -rf $DB_HOME/.patch_storage $DB_HOME/.opatchauto_storage $GRID_HOME/.patch_storage $GRID_HOME/.opatchauto_storage
# hadolint ignore=DL3006
COPY  --from=builder /u01 /u01
# hadolint ignore=SC2086
RUN if [ "${SLIMMING}x" != 'truex' ]; then \
       $INVENTORY/orainstRoot.sh && \
       $GRID_HOME/root.sh && \
       $DB_HOME/root.sh && \
       chmod 666 $SCRIPT_DIR/*.rsp && \
       :; \
    fi && \
    $INSTALL_DIR/install/$FIXUP_PREQ_FILE && \
    sync && \
    chmod 755 $SCRIPT_DIR/*.sh && \
    chmod 755 $SCRIPT_DIR/scripts/*.py && \
    chmod 755 $SCRIPT_DIR/scripts/cmdExec && \
    chmod 755 $SCRIPT_DIR/scripts/*.expect && \
    echo "nohup $SCRIPT_DIR/runOracle.sh &" >> /etc/rc.local && \
    chmod +x /etc/rc.d/rc.local  && \
    cp $SCRIPT_DIR/$INITSH /usr/bin/$INITSH && \
    setcap 'cap_net_admin,cap_net_raw+ep' /usr/bin/ping && \
    chmod 755 /usr/bin/$INITSH && \ 
    rm -f $INSTALL_DIR/install/* && \
    rm -rf $DB_HOME/.patch_storage $DB_HOME/.opatchauto_storage $GRID_HOME/.patch_storage $GRID_HOME/.opatchauto_storage && \
    sync

USER ${USER}
VOLUME ["/common_scripts"]
WORKDIR $WORKDIR

# Define default command to start Oracle Grid and RAC Database setup.

# Define default command to start Oracle Grid and RAC Database setup.
# hadolint ignore=DL3025
ENTRYPOINT /usr/bin/$INITSH