#! /bin/bash

echo "Creating env variables file /etc/rac_env_vars"
/bin/bash -c "cat /proc/1/environ | tr '\0' '\n' > /etc/rac_env_vars"
/bin/bash -c "sed -i -e 's/^/export /' /etc/rac_env_vars"

echo "Starting Systemd"
exec /lib/systemd/systemd
