## Copyright (c) 2021, 2024, Oracle and/or its affiliates.
version: '2'
services:
  ogg:
    image: oracle/goldengate:23.4
    build:
      context: ../
      args:                         ## The INSTALLER build argument is required
        INSTALLER:    234000_fbo_ggs_Linux_x64_Oracle_services_shiphome.zip
    environment:
      OGG_ADMIN:      oggadmin      ## Administrative account name
      OGG_DEPLOYMENT: Sample        ## Name of OGG Deployment
    volumes:
      - oggdata:/u02                ## Persistent GoldenGate data
      - oggtemp:/u03                ## Temporary GoldenGate data
      - ../cert:/etc/nginx/cert     ## Certificate and key for SSL
    ports:
      - 8443:443                    ## Host port mapping for HTTPS access
volumes:
  oggdata:
  oggtemp:                          ## Includes Cache Manager files, so this
    driver_opts:                    ##  volume could get large. Using tmpfs
      type:   tmpfs                 ##  is not appropriate for all cases.
      device: tmpfs
