---
version: "3"
networks:
  rac_pub1_nw:
    name: ${PUBLIC_NETWORK_NAME}
    external: true
  rac_priv1_nw:
    name: ${PRIVATE1_NETWORK_NAME}
    external: true
  rac_priv2_nw:
    name: ${PRIVATE2_NETWORK_NAME}
    external: true
secrets:
  pwdsecret:
    file: ${PWD_SECRET_FILE}
  keysecret:
    file: ${KEY_SECRET_FILE}
services:
  racnodep3:
    container_name: ${RACNODE3_CONTAINER_NAME}
    hostname: ${RACNODE3_HOST_NAME}
    image: ${RAC_IMAGE_NAME}
    restart: always
    dns: ${DNS_PUBLIC_IP}
    dns_search: ${DNS_DOMAIN}
    shm_size: 4G
    secrets:
      - pwdsecret
      - keysecret
    volumes:
      - ${GRID_RESPONSE_FILE}:/tmp/grid_21ai.rsp
    environment:
      DNS_SERVERS: ${DNS_PUBLIC_IP}
      PRIVATE_IP1_LIST: ${RACNODE3_PRIVATE_IP1_LIST}
      PRIVATE_IP2_LIST: ${RACNODE3_PRIVATE_IP2_LIST}
      DEFAULT_GATEWAY: ${DEFAULT_GATEWAY}
      INSTALL_NODE: ${INSTALL_NODE}
      OP_TYPE: racaddnode
      EXISTING_CLS_NODE: ${EXISTING_CLS_NODE}
      CRS_NODES: ${CRS_NODES}
      SCAN_NAME: ${SCAN_NAME}
      PROFILE_FLAG: "true"
      DB_PWD_FILE: pwdsecret
      PWD_KEY: keysecret
      CRS_ASM_DEVICE_LIST: ${CRS_ASM_DEVICE_LIST}
      CRS_ASM_DISCOVERY_DIR: ${CRS_ASM_DISCOVERY_DIR}
      INIT_SGA_SIZE: 3G
      INIT_PGA_SIZE: 2G
      GRID_RESPONSE_FILE: /tmp/grid_21ai.rsp
    sysctls:
        - kernel.shmall=2097152
        - kernel.shmmax=8589934592
        - kernel.shmmni=4096
        - 'kernel.sem=250 32000 100 128'
        - 'net.ipv4.conf.eth1.rp_filter=2'
        - 'net.ipv4.conf.eth2.rp_filter=2'
    ulimits:
      rtprio: 99
    cap_add:
      - SYS_RESOURCE
      - NET_ADMIN
      - SYS_NICE
      - AUDIT_WRITE
      - AUDIT_CONTROL
    devices:
      - "${ASM_DISK1}:${ASM_DEVICE1}"
      - "${ASM_DISK2}:${ASM_DEVICE2}"
    networks:
      - rac_pub1_nw
      - rac_priv1_nw
      - rac_priv2_nw
    healthcheck:
      test: ["CMD-SHELL", "if [ `cat /tmp/orod/oracle_rac_setup.log | grep -c 'ORACLE RAC DATABASE IS READY TO USE'` -ge 1 ]; then exit 0; else exit 1; fi"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}