# hadolint global ignore=DL4006
# LICENSE UPL 1.0
#
# Copyright (c) 2018,2021 Oracle and/or its affiliates.
#
# ORACLE CONTAINERFILES PROJECT
# --------------------------
# This is the Containerfile for Oracle GSM 21c Release 3 to build the container image
# MAINTAINER <paramdeep.saini@oracle.com>
#
# This is the Containerfile for Oracle GSM  21c
#
# REQUIRED FILES TO BUILD THIS IMAGE
# ----------------------------------
# (1) LINUX.X64_213000_gsm.zip
#     Download Oracle Database 21c GSM Software
#     from http://www.oracle.com/technetwork/database/enterprise-edition/downloads/index.html
#
# HOW TO BUILD THIS IMAGE
# -----------------------
# Put all downloaded files in the same directory as this Containerfile
# Run:
#      $ podman build -t oracle/gsm:21.3.0 .
#
# Pull base image
# ---------------
ARG BASE_IMAGE=oraclelinux:7-slim
ARG BASE_OL_IMAGE=$BASE_IMAGE
ARG BASE_IMAGE_REF=oraclelinux:7-slim
ARG BASE_IMAGE_DIGEST=unknown

# Pull base image
# ---------------
# hadolint ignore=DL3006,DL3025
FROM $BASE_OL_IMAGE AS base
RUN \
      mkdir -p /usr/share/oracle/image-metadata/rpms && \
      rpm -qa --qf '%{NAME}-%{VERSION}-%{RELEASE}.%{ARCH}\n' | sort > /usr/share/oracle/image-metadata/rpms/base-image-rpms.txt && \
      rpm -qa --qf '%{NAME}\n' | sort -u > /usr/share/oracle/image-metadata/rpms/base-image-rpm-names.txt;
ARG BASE_IMAGE
ARG BASE_IMAGE_REF
ARG BASE_IMAGE_DIGEST
LABEL "org.opencontainers.image.base.name"="$BASE_IMAGE_REF" \
      "org.opencontainers.image.base.digest"="$BASE_IMAGE_DIGEST" \
      "com.oracle.database.base.image.chain.path"="/usr/share/oracle/image-metadata/base-image-chain.json"
ARG VERSION

# Labels
# ------
LABEL "provider"="Oracle"                                          \
      "issues"="https://github.com/oracle/docker-images/issues"    \
      "volume.setup.location1"="/opt/oracle/scripts"               \
      "port.listener"="1522"

# Argument to control removal of components not needed after db software installation
ARG SLIMMING=false
ARG INSTALL_FILE_1="LINUX.X64_213000_gsm.zip"

# Environment variables required for this build (do NOT change)
# -------------------------------------------------------------
ENV GSM_BASE="/u01/app/oracle" \
    GSM_HOME="/u01/app/oracle/product/21c/gsmhome_1" \
    INVENTORY="/u01/app/oracle/oraInventory" \
    INSTALL_DIR="/opt/oracle/scripts" \
    INSTALL_FILE_1=$INSTALL_FILE_1 \
    INSTALL_RSP="21c_gsm_install.rsp" \
    RUN_FILE="runOracle.sh" \
    SETUP_LINUX_FILE="setupLinuxEnv.sh" \
    CHECK_SPACE_FILE="checkSpace.sh" \
    USER_SCRIPTS_FILE="runUserScripts.sh" \
    INSTALL_GSM_BINARIES_FILE="installGSMBinaries.sh" \
    GSM_SETUP_FILE="setupOshardEnv.sh"  \
    GSM_ENV_SETUP_FILE="setupGSM.sh" \
    GSM_SCRIPTS="scripts" \
    MAINPY="main.py" \
    PYTHON_FILE="/usr/bin/python" \
    PYTHON3_FILE="/usr/bin/python3" \
    CHECKLIVENESS="checkLiveness.sh"
# Use second ENV so that variable get substituted
# hadolint ignore=DL3044
ENV  INSTALL_SCRIPTS=$INSTALL_DIR/install \
     ORACLE_HOME=$GSM_HOME \
     ORACLE_BASE=$GSM_BASE \
     SCRIPT_DIR=$INSTALL_DIR/sharding \
     SHARD_SCRIPT_DIR=$INSTALL_DIR/sharding \
     PATH=/bin:/usr/bin:/sbin:/usr/sbin \
     GSM_PATH=$GSM_HOME/bin:$PATH \
     GSM_LD_LIBRARY_PATH=$GSM_HOME/lib:/usr/lib:/lib


# Copy files needed during both installation and runtime
# ------------
COPY $VERSION/$SETUP_LINUX_FILE $VERSION/$CHECK_SPACE_FILE $VERSION/$GSM_ENV_SETUP_FILE $INSTALL_DIR/install/
COPY $VERSION/$RUN_FILE $VERSION/$GSM_SETUP_FILE $VERSION/$CHECKLIVENESS $VERSION/$USER_SCRIPTS_FILE $SCRIPT_DIR/
COPY $GSM_SCRIPTS $SCRIPT_DIR/scripts/

RUN chmod 755 $INSTALL_DIR/install/*.sh && \
    sync && \
    $INSTALL_DIR/install/$CHECK_SPACE_FILE && \
    $INSTALL_DIR/install/$SETUP_LINUX_FILE && \
    $INSTALL_DIR/install/$GSM_ENV_SETUP_FILE  && \
    sync

#############################################
# -------------------------------------------
# Start new stage for installing the GSM
# -------------------------------------------
#############################################

from base AS builder
ARG VERSION

COPY $VERSION/$INSTALL_FILE_1 $VERSION/$INSTALL_RSP $VERSION/$INSTALL_GSM_BINARIES_FILE $VERSION/$GSM_SETUP_FILE $INSTALL_DIR/install/

# hadolint ignore=SC2086
RUN chmod 755 $INSTALL_SCRIPTS/*.sh  && \
    sync && \
    sed -e '/hard *memlock/s/^/#/g' -i /etc/security/limits.d/oracle-database-preinstall-21c.conf && \
    sed -e '/ *nofile /s/^/#/g' -i /etc/security/limits.d/oracle-database-preinstall-21c.conf && \
    su oracle -c "$INSTALL_DIR/install/$INSTALL_GSM_BINARIES_FILE" && \
    $INVENTORY/orainstRoot.sh && \
    $GSM_HOME/root.sh && \
    rm -rf $INSTALL_DIR/install && \
    rm -f /etc/sysctl.d/99-oracle-database-preinstall-21c-sysctl.conf && \
    rm -f /etc/sysctl.d/99-sysctl.conf && \
    rm -f /etc/rc.d/init.d/oracle-database-preinstall-21c-firstboot && \
    rm -f /etc/security/limits.d/oracle-database-preinstall-21c.conf && \
    sync

#############################################
# -------------------------------------------
# Start new layer for GSM runtime
# -------------------------------------------
#############################################

FROM base
ARG BASE_IMAGE
ARG BASE_IMAGE_REF
ARG BASE_IMAGE_DIGEST
RUN mkdir -p /usr/share/oracle/image-metadata && \
    printf '{\n  "schemaVersion": 1,\n  "images": [{"name": "%s", "digest": "%s", "reference": "%s", "role": "direct-base"}]\n}\n' \
      "$BASE_IMAGE_REF" "$BASE_IMAGE_DIGEST" "$BASE_IMAGE" > /usr/share/oracle/image-metadata/base-image-chain.json

RUN \
      rpm -qa --qf '%{NAME}-%{VERSION}-%{RELEASE}.%{ARCH}\n' | sort > /usr/share/oracle/image-metadata/rpms/image-rpms.txt && \
      rpm -qa --qf '%{NAME}	%{VERSION}-%{RELEASE}.%{ARCH}\n' | sort > /tmp/image-rpm-details && \
      if [ -f /usr/share/oracle/image-metadata/rpms/base-image-rpm-names.txt ]; then \
        awk -F '\t' 'NR==FNR {base[$1]=1; next} !($1 in base) {print $1 "-" $2}' /usr/share/oracle/image-metadata/rpms/base-image-rpm-names.txt /tmp/image-rpm-details > /usr/share/oracle/image-metadata/rpms/image-added-rpms.txt; \
      else \
        cp /usr/share/oracle/image-metadata/rpms/image-rpms.txt /usr/share/oracle/image-metadata/rpms/image-added-rpms.txt; \
      fi && \
      rm -f /tmp/image-rpm-details;

COPY --from=builder /u01 /u01

# hadolint ignore=SC2086
RUN if [ ! -f $PYTHON_FILE ]; then \
      ln -s $PYTHON3_FILE $PYTHON_FILE && \
      :; \
    fi && \
    rm -f $INSTALL_DIR/install/*  && \
    cp $SCRIPT_DIR/scripts/cmdExec  $SCRIPT_DIR/ && \
    for helper in cmdExec main.py orapcatalog.py orapshard.py orascatalog.py oracommon.py demoapp.sql runOraShardSetup.sh oramachine.py oralogger.py orafactory.py oragsm.py orasshard.py oraenv.py; do \
      ln -sf scripts/$helper $SHARD_SCRIPT_DIR/$helper; \
    done && \
    ln -sf ../$CHECKLIVENESS $SCRIPT_DIR/scripts/$CHECKLIVENESS && \
    chown -R oracle:oinstall $SCRIPT_DIR && \
    chmod 755 $SCRIPT_DIR/*.sh && \
    chmod 755 $SCRIPT_DIR/scripts/*.py && \
    chmod 755 $SCRIPT_DIR/scripts/*.sh && \
    chmod 755 $SCRIPT_DIR/scripts/cmdExec && \
    chmod 755 $SCRIPT_DIR/cmdExec && \
    sync

USER  oracle
WORKDIR /home/oracle
EXPOSE 1521

VOLUME ["$GSM_BASE/oradata"]

HEALTHCHECK --interval=2m --start-period=25m \
   CMD "$SCRIPT_DIR/$CHECKLIVENESS" >/dev/null || exit 1

# Define default command to start Oracle Database.
# hadolint ignore=DL3025
CMD exec $SCRIPT_DIR/$RUN_FILE
