# Copyright 2020, Oracle Corporation and/or affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl
# MAINTAINER <paramdeep.saini@oracle.com>
#
# This is the Dockerfile for Oracle Database 21
#
# REQUIRED FILES TO BUILD THIS IMAGE
# ----------------------------------
# (1) LINUX.X64_213000_gsm.zip
#     Download Oracle Database 21c GSM Software
#     from http://www.oracle.com/technetwork/database/enterprise-edition/downloads/index.html
#
# HOW TO BUILD THIS IMAGE
# -----------------------
# Put all downloaded files in the same directory as this Dockerfile
# Run:
#      $ docker build -t oracle/gsm:21.3.0 .
#
# Pull base image
# ---------------
ARG BASE_IMAGE=oraclelinux:7-slim
ARG BASE_IMAGE_REF=oraclelinux:7-slim
ARG BASE_IMAGE_DIGEST=unknown
FROM $BASE_IMAGE as base
ARG BASE_IMAGE
ARG BASE_IMAGE_REF
ARG BASE_IMAGE_DIGEST
LABEL "org.opencontainers.image.base.name"="$BASE_IMAGE_REF" \
      "org.opencontainers.image.base.digest"="$BASE_IMAGE_DIGEST" \
      "com.oracle.database.base.image.chain.path"="/usr/share/oracle/image-metadata/base-image-chain.json"

# Maintainer
# ----------
MAINTAINER Paramdeep Saini <paramdeep.saini@oracle.com>

# Environment variables required for this build (do NOT change)
# -------------------------------------------------------------
ENV GSM_BASE="/u01/app/oracle" \
    GSM_HOME="/u01/app/oracle/product/21c/gsmhome_1" \
    INVENTORY="/u01/app/oraInventory" \
    INSTALL_DIR="/opt/scripts" \
    INSTALL_FILE_1="LINUX.X64_213000_gsm.zip" \
    INSTALL_RSP="21c_gsm_install.rsp" \
    RUN_FILE="runOracle.sh" \
    SETUP_LINUX_FILE="setupLinuxEnv.sh" \
    CHECK_SPACE_FILE="checkSpace.sh" \
    USER_SCRIPTS_FILE="runUserScripts.sh" \
    INSTALL_GSM_BINARIES_FILE="installGSMBinaries.sh" \
    GSM_SETUP_FILE="setupOshardEnv.sh"  \
    GSM_ENV_SETUP_FILE="setupGSM.sh" \
    GSM_SCRIPTS="scripts"
# Use second ENV so that variable get substituted
ENV  INSTALL_SCRIPTS=$INSTALL_DIR/install \
     ORACLE_HOME=$GSM_HOME \
     ORACLE_BASE=$GSM_BASE \
     SCRIPT_DIR=$INSTALL_DIR/startup \
     PATH=/bin:/usr/bin:/sbin:/usr/sbin:$PATH \
     GSM_PATH=$GSM_HOME/bin:/usr/sbin:$PATH \
     GSM_LD_LIBRARY_PATH=$GSM_HOME/lib:/usr/lib:/lib 
    

# Copy files needed during both installation and runtime
# ------------
COPY $INSTALL_FILE_1 $SETUP_LINUX_FILE $CHECK_SPACE_FILE $INSTALL_RSP $GSM_ENV_SETUP_FILE $INSTALL_GSM_BINARIES_FILE $GSM_SETUP_FILE $INSTALL_DIR/install/
COPY $RUN_FILE $GSM_SETUP_FILE $USER_SCRIPTS_FILE $INSTALL_DIR/startup/ 
COPY $GSM_SCRIPTS $INSTALL_DIR/startup/scripts

RUN chmod 755 $INSTALL_DIR/install/*.sh && \
    sync && \
    $INSTALL_DIR/install/$CHECK_SPACE_FILE && \
    $INSTALL_DIR/install/$SETUP_LINUX_FILE && \
    $INSTALL_DIR/install/$GSM_ENV_SETUP_FILE  && \
    sed -e '/hard *memlock/s/^/#/g' -i /etc/security/limits.d/oracle-database-preinstall-19c.conf && \
    su oracle -c "$INSTALL_DIR/install/$INSTALL_GSM_BINARIES_FILE" && \
    $INVENTORY/orainstRoot.sh && \
    $GSM_HOME/root.sh && \
    rm -rf $INSTALL_DIR/install && \
    rm -f /etc/sysctl.d/99-oracle-database-preinstall-19c-sysctl.conf && \
    rm -f /etc/sysctl.d/99-sysctl.conf && \
    rm -f /etc/rc.d/init.d/oracle-database-preinstall-19c-firstboot && \
    rm -f /etc/security/limits.d/oracle-database-preinstall-19c.conf && \
    rm -f $INSTALL_DIR/install/*  && \
    chown -R oracle:oinstall $SCRIPT_DIR && \
    chmod 755 $SCRIPT_DIR/*.sh && \
    sync

RUN mkdir -p /usr/share/oracle/image-metadata && \
    printf '{\n  "schemaVersion": 1,\n  "images": [{"name": "%s", "digest": "%s", "reference": "%s", "role": "direct-base"}]\n}\n' \
      "$BASE_IMAGE_REF" "$BASE_IMAGE_DIGEST" "$BASE_IMAGE" > /usr/share/oracle/image-metadata/base-image-chain.json

USER  oracle
WORKDIR /home/oracle
EXPOSE 1521

VOLUME ["$GSM_BASE/oradata"]

# Define default command to start Oracle Database.
CMD exec $INSTALL_DIR/startup/$RUN_FILE
